seed: 42
batch_size: 8
num_workers: 4
epochs: 20

# dataset

data_path: ./processed_data/stimuli_original_dino_vision.pkl
captions_path: ./processed_data/stimuli_original_captions.pkl
train_idx_path: ./processed_data/subj01/sig_train_sub1.pkl
test_idx_path: ./processed_data/subj01/sig_test_sub1.pkl
prefix_length: 10
gpt2_type: gpt2
normalize_prefix: False


# model
mapping_network:
  only_prefix: False
  prefix_length: 10
  clip_length: 10
  prefix_size: 1536 # embed of vis feature
  num_layers: 8
  mapping_type: transformer

# optimizer
lr: 0.00002
num_warmup_steps: 5000